import 'package:flutter/material.dart';

/// Immutable catalog metadata used to present and launch one slot theme.
class GameDefinition {
  const GameDefinition({
    required this.id,
    required this.name,
    required this.asset,
    required this.symbolSet,
    required this.jackpot,
    required this.unlockLevel,
    required this.features,
    required this.primary,
    required this.secondary,
    required this.category,
    required this.packageVersion,
    required this.packageSizeMb,
    this.bundled = false,
    this.isNew = false,
    this.featured = false,
    this.bonusBuyMultiplier,
  });

  final String id, name, asset, symbolSet, jackpot, features;
  final int unlockLevel;
  final int packageVersion, packageSizeMb;
  final int? bonusBuyMultiplier;
  final String category;
  final bool bundled, isNew, featured;
  final Color primary, secondary;
}

const games = [
  GameDefinition(
    id: 'pharaoh-oasis',
    name: 'PHARAOH OASIS',
    asset: 'assets/slots/pharaoh_oasis.png',
    symbolSet: 'pharaoh',
    jackpot: '72.450.000',
    unlockLevel: 1,
    features: 'EXPANDING WILDS • 2× FREE SPINS • RESPINS',
    primary: Color(0xffffb52c),
    secondary: Color(0xff6b2bd9),
    category: 'ANCIENT',
    packageVersion: 2,
    packageSizeMb: 18,
    bundled: true,
    featured: true,
  ),
  GameDefinition(
    id: 'dragon-peak',
    name: 'DRAGON PEAK',
    asset: 'assets/slots/dragon_peak.png',
    symbolSet: 'dragon',
    jackpot: '58.320.000',
    unlockLevel: 4,
    features: 'CASCADES • DRAGON WILDS • ULTIMATE FREE SPINS ×2→×5',
    primary: Color(0xffff5b25),
    secondary: Color(0xff821411),
    category: 'ADVENTURE',
    packageVersion: 3,
    packageSizeMb: 21,
    bundled: true,
    featured: true,
  ),
  GameDefinition(
    id: 'candy-carnival',
    name: 'CANDY CARNIVAL',
    asset: 'assets/slots/candy_carnival.png',
    symbolSet: 'candy',
    jackpot: '41.680.000',
    unlockLevel: 8,
    features: '32–3125 VARIABLE WAYS • STICKY WILDS • CASCADES',
    primary: Color(0xffff4fc3),
    secondary: Color(0xff7b2cff),
    category: 'CASCADE',
    packageVersion: 4,
    packageSizeMb: 17,
    bundled: true,
  ),
  GameDefinition(
    id: 'pirate-bay',
    name: 'PIRATE BAY',
    asset: 'assets/slots/pirate_bay.png',
    symbolSet: 'pirate',
    jackpot: '96.750.000',
    unlockLevel: 12,
    features: '3× FREE SPINS • COIN COLLECT • TREASURE PICK',
    primary: Color(0xff24a9df),
    secondary: Color(0xff073f8c),
    category: 'BONUS GAMES',
    packageVersion: 3,
    packageSizeMb: 24,
    isNew: true,
    featured: true,
    bonusBuyMultiplier: 50,
  ),
  GameDefinition(
    id: 'neon-nights',
    name: 'NEON NIGHTS',
    asset: 'assets/slots/neon_nights.png',
    symbolSet: 'neon',
    jackpot: '88.400.000',
    unlockLevel: 5,
    features: 'WALKING WILDS • ×2 MULTIPLIER SYMBOLS • 8 FREE SPINS',
    primary: Color(0xffff35dc),
    secondary: Color(0xff1369ff),
    category: 'LOW VOLATILITY',
    packageVersion: 3,
    packageSizeMb: 19,
    isNew: true,
  ),
  GameDefinition(
    id: 'frozen-kingdom',
    name: 'FROZEN KINGDOM',
    asset: 'assets/slots/frozen_kingdom.png',
    symbolSet: 'frozen',
    jackpot: '64.750.000',
    unlockLevel: 7,
    features: 'STACKED ICE WILDS • STICKY WILDS • 5 FREE SPINS',
    primary: Color(0xff52e7ff),
    secondary: Color(0xff2453b8),
    category: 'FREE SPINS',
    packageVersion: 3,
    packageSizeMb: 20,
  ),
  GameDefinition(
    id: 'jungle-temple',
    name: 'JUNGLE TEMPLE',
    asset: 'assets/slots/jungle_temple.png',
    symbolSet: 'jungle',
    jackpot: '105.600.000',
    unlockLevel: 15,
    features: 'CASCADES UP TO 12× • SYMBOL UPGRADES • TEMPLE WHEEL',
    primary: Color(0xffffc82f),
    secondary: Color(0xff087a55),
    category: 'MEGA FEATURES',
    packageVersion: 3,
    packageSizeMb: 25,
    isNew: true,
    featured: true,
    bonusBuyMultiplier: 50,
  ),
  GameDefinition(
    id: 'vegas-gold',
    name: 'VEGAS GOLD',
    asset: 'assets/slots/vegas_gold.png',
    symbolSet: 'vegas',
    jackpot: '150.000.000',
    unlockLevel: 20,
    features: 'BOTH WAYS • HOLD & WIN • 4 JACKPOTS',
    primary: Color(0xffffc52f),
    secondary: Color(0xff8b101c),
    category: 'CLASSIC VEGAS',
    packageVersion: 3,
    packageSizeMb: 23,
    isNew: true,
    bonusBuyMultiplier: 50,
  ),
];
